INSERT INTO localidad (id_localidad,nombre) VALUES (1,"ALHAURIN DE LA TORRE");
INSERT INTO localidad (id_localidad,nombre) VALUES (2,"ALHAURIN EL GRANDE");
INSERT INTO localidad (id_localidad,nombre) VALUES (3,"ALAMEDA");
INSERT INTO localidad (id_localidad,nombre) VALUES (4,"ALFARNATE");
INSERT INTO localidad (id_localidad,nombre) VALUES (5,"ALGARROBO");
INSERT INTO localidad (id_localidad,nombre) VALUES (6,"ALCAUCIN");
INSERT INTO localidad (id_localidad,nombre) VALUES (7,"ALGECIRAS");
INSERT INTO localidad (id_localidad,nombre) VALUES (8,"ALMARGEN");
INSERT INTO localidad (id_localidad,nombre) VALUES (9,"ALMOGIA");
INSERT INTO localidad (id_localidad,nombre) VALUES (10,"ALORA");
INSERT INTO localidad (id_localidad,nombre) VALUES (11,"ALOZAINA");
INSERT INTO localidad (id_localidad,nombre) VALUES (12,"ANTEQUERA");
INSERT INTO localidad (id_localidad,nombre) VALUES (13,"ARCHIDONA");
INSERT INTO localidad (id_localidad,nombre) VALUES (14,"ARDALES");
INSERT INTO localidad (id_localidad,nombre) VALUES (15,"ARRIATE");
INSERT INTO localidad (id_localidad,nombre) VALUES (16,"BENAGALBON");
INSERT INTO localidad (id_localidad,nombre) VALUES (17,"BENAHAVIS");
INSERT INTO localidad (id_localidad,nombre) VALUES (18,"BENALMADENA");
INSERT INTO localidad (id_localidad,nombre) VALUES (19,"BENALMOCARRA");
INSERT INTO localidad (id_localidad,nombre) VALUES (20,"BENAOJAN");
INSERT INTO localidad (id_localidad,nombre) VALUES (21,"CAMPANILLAS");
INSERT INTO localidad (id_localidad,nombre) VALUES (22,"CAMPILLOS");
INSERT INTO localidad (id_localidad,nombre) VALUES (23,"CAÑETE LA REAL");
INSERT INTO localidad (id_localidad,nombre) VALUES (24,"CARRATRACA");
INSERT INTO localidad (id_localidad,nombre) VALUES (25,"CARTAMA");
INSERT INTO localidad (id_localidad,nombre) VALUES (26,"CASABERMEJA");
INSERT INTO localidad (id_localidad,nombre) VALUES (27,"CASARABONELA");
INSERT INTO localidad (id_localidad,nombre) VALUES (28,"CASARES");
INSERT INTO localidad (id_localidad,nombre) VALUES (29,"CHURRIANA");
INSERT INTO localidad (id_localidad,nombre) VALUES (30,"COIN");
INSERT INTO localidad (id_localidad,nombre) VALUES (31,"COMPETA");
INSERT INTO localidad (id_localidad,nombre) VALUES (32,"CORDOBA");
INSERT INTO localidad (id_localidad,nombre) VALUES (33,"CUEVAS DE SAN MARCOS");
INSERT INTO localidad (id_localidad,nombre) VALUES (34,"CUEVAS DEL BECERRO");
INSERT INTO localidad (id_localidad,nombre) VALUES (35,"EL BURGO");
INSERT INTO localidad (id_localidad,nombre) VALUES (36,"ESTEPONA");
INSERT INTO localidad (id_localidad,nombre) VALUES (37,"FRIGILIANA");
INSERT INTO localidad (id_localidad,nombre) VALUES (38,"FUENGIROLA");
INSERT INTO localidad (id_localidad,nombre) VALUES (39,"FUENTEPIEDRA");
INSERT INTO localidad (id_localidad,nombre) VALUES (40,"GUARO");
INSERT INTO localidad (id_localidad,nombre) VALUES (41,"HUMILLADERO");
INSERT INTO localidad (id_localidad,nombre) VALUES (42,"ISTAN");
INSERT INTO localidad (id_localidad,nombre) VALUES (43,"JAEN");
INSERT INTO localidad (id_localidad,nombre) VALUES (40,"MALAGA CAPITAL");
